### ISSUE TITLE
catkin_make error

### ISSUE THREAD

**Issue by edgar-explorer** [slightech/MYNT-EYE-SDK#1]
rosfun@cc-B250-HD3:~/dev/catkin_ws$ catkin_make
Base path: /home/rosfun/dev/catkin_ws
Source space: /home/rosfun/dev/catkin_ws/src
Build space: /home/rosfun/dev/catkin_ws/build
Devel space: /home/rosfun/dev/catkin_ws/devel
Install space: /home/rosfun/dev/catkin_ws/install
####
####
####
####
[ 11%] Built target zed_wrapper_gencfg
[ 33%] Built target MYNTWrapper
[ 44%] Linking CXX executable /home/rosfun/dev/catkin_ws/devel/lib/mynteye_ros_wrapper/mynteye_wrapper_node
[ 66%] Built target ZEDWrapper
[ 77%] Linking CXX executable /home/rosfun/dev/catkin_ws/devel/lib/zed_wrapper/zed_wrapper_node
CMakeFiles/mynteye_wrapper_node.dir/src/mynteye_ros_wrapper_node.cpp.o: In function `main':
mynteye_ros_wrapper_node.cpp:(.text.startup+0x4d): undefined reference to `ros::init(int&, char**, std::string const&, unsigned int)'
mynteye_ros_wrapper_node.cpp:(.text.startup+0x7a): undefined reference to `ros::names::getRemappings()'
mynteye_ros_wrapper_node.cpp:(.text.startup+0x15a): undefined reference to `ros::this_node::getName()'
mynteye_ros_wrapper_node.cpp:(.text.startup+0x17c): undefined reference to `nodelet::Loader::load(std::string const&, std::string const&, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, std::vector<std::string, std::allocator<std::string> > const&)'
collect2: error: ld returned 1 exit status
MYNT-EYE-ROS-Wrapper/CMakeFiles/mynteye_wrapper_node.dir/build.make:205: recipe for target '/home/rosfun/dev/catkin_ws/devel/lib/mynteye_ros_wrapper/mynteye_wrapper_node' failed
make[2]: *** [/home/rosfun/dev/catkin_ws/devel/lib/mynteye_ros_wrapper/mynteye_wrapper_node] Error 1
CMakeFiles/Makefile2:424: recipe for target 'MYNT-EYE-ROS-Wrapper/CMakeFiles/mynteye_wrapper_node.dir/all' failed
make[1]: *** [MYNT-EYE-ROS-Wrapper/CMakeFiles/mynteye_wrapper_node.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/zed_wrapper_node.dir/src/zed_wrapper_node.cpp.o: In function `main':
zed_wrapper_node.cpp:(.text.startup+0x56): undefined reference to `ros::init(int&, char**, std::string const&, unsigned int)'
zed_wrapper_node.cpp:(.text.startup+0x89): undefined reference to `ros::names::getRemappings()'
zed_wrapper_node.cpp:(.text.startup+0x15a): undefined reference to `ros::this_node::getName()'
zed_wrapper_node.cpp:(.text.startup+0x173): undefined reference to `nodelet::Loader::load(std::string const&, std::string const&, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, std::vector<std::string, std::allocator<std::string> > const&)'
collect2: error: ld returned 1 exit status
zed-ros-wrapper/CMakeFiles/zed_wrapper_node.dir/build.make:438: recipe for target '/home/rosfun/dev/catkin_ws/devel/lib/zed_wrapper/zed_wrapper_node' failed
make[2]: *** [/home/rosfun/dev/catkin_ws/devel/lib/zed_wrapper/zed_wrapper_node] Error 1
CMakeFiles/Makefile2:2474: recipe for target 'zed-ros-wrapper/CMakeFiles/zed_wrapper_node.dir/all' failed
make[1]: *** [zed-ros-wrapper/CMakeFiles/zed_wrapper_node.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed

**Comment by joinAero** [comment]
$ rosversion -d

**Comment by joinAero** [comment]
Try to `catkin_make` in a new directory `~/catkin_ws_mynt`:

```
$ mkdir -p ~/catkin_ws_mynt/src

$ cd ~/catkin_ws_mynt/src
$ git clone https://github.com/slightech/MYNT-EYE-ROS-Wrapper.git

$ cd ..
$ catkin_make

$ source ~/catkin_ws_mynt/devel/setup.bash
```

And what's your ros version?

```
$ rosversion -d
$ rosversion roscpp
```

However, the `roscpp` library is not correctly linked now ([roscpp api doc](http://docs.ros.org/api/roscpp/html/)):

    undefined reference to ros::init(...)

Besides, you can also google "undefined reference to ros::init".
