### ISSUE TITLE
update failure

### ISSUE THREAD

**Issue by ghost** [slightech/MYNT-EYE-SDK#11]
I attempted to update the firmware from 0103 to 0105 using setup.exe. Since the status "Choosing ...." does not change much, quit the application, unplug the plug, and then connect it, the camera will not recognize it.

Is this camera device no longer usable?

**Comment by ghost** [comment]
Sorry, I was able to solve it by looking at the tutorial.

**Comment by ghost** [comment]
I updated the camera to 0105 and restarted the application, but I got only 25 FPS. How can we make it to 50 FPS?

**Comment by enteguo** [comment]
@takuhara hello，I update the firmwork to 0103, now my computer cant recognize cam.

**Comment by ghost** [comment]
After installing mynteye-1.7-linux-x64-gcc4-opencv-3.2.0.tar.gz, it came out 50 FPS.
At 1.5, 25 FPS was the limit.
