### ISSUE TITLE
error:'put_time' is not a member of 'std'

### ISSUE THREAD

**Issue by cxzhp** [slightech/MYNT-EYE-SDK#12]
![a](https://user-images.githubusercontent.com/9394970/34923902-da39e020-f9da-11e7-96e4-1b47b9007d9b.png)

**Comment by cxzhp** [comment]
问题解决了：

1. 快速处理的方法：

先注释掉这一行代码，再编译。  因为这个报错是test部分，不影响摄像头的功能使用的。

2. 具体原因如下：
首先，SDK代码没问题的，这个 API 很简单。
先 camera_test.cc 里，直接保留以下红框里的代码就可以了：

![aa](https://user-images.githubusercontent.com/9394970/34925642-922d8736-f9e5-11e7-84e5-25262162e839.png)

报这个错，有两个可能： 1) 要么是你 cmake 版本没检测出 OS_LINUX， 2) 要么是你 GCC 没支持此 API

1. samples/cmake/Common.cmake 里检测了 OS_LINUX
2. camera_test.cc 里是用 std::put_time() 格式化显示时间用而已 3. std::put_time 是 c++ 11 引入的 API ，是会有些编译器（或其不同版本）实现了，有些没有。
![aaa](https://user-images.githubusercontent.com/9394970/34925660-ae4583d8-f9e5-11e7-8465-ba8fe60ed4dd.png)

3. camera_test.cc 是测试：图像和 IMU 数量及其比例，IMU 时间戳顺序的。

4. 这个问题，也可以在 camera_test.cc 里加上以下代码片段：
![aaaa](https://user-images.githubusercontent.com/9394970/34925676-c01329ee-f9e5-11e7-9430-239b88663a52.png)

附上文字版：
#ifdef _WIN32
    #define OS_WIN
#elif __linux__
    #define OS_LINUX
#endif

**Comment by yangruixuan** [comment]
Will fixed in future build
