### ISSUE TITLE
SetAutoExposureEnabled failure

### ISSUE THREAD

**Issue by ghost** [slightech/MYNT-EYE-SDK#13]
my environment is 
  mynteye-1.7-linux-x64-gcc5-opencv-3.2.0.tar.gz
  mynteye_0105_1711181427.img | 0105

In MYNT-EYE-ROS-Wrapper,
SetAutoExposureEnabled fails.

why??

**Comment by joinAero** [comment]
When you run samples, e.g. camera2, it prints "AutoExposure supported" or "not supported"?

**Comment by joinAero** [comment]
You could set it using Previewer (menu control). And the firmware will store it.
