### ISSUE TITLE
Special Builds??

### ISSUE THREAD

**Issue by ghost** [slightech/MYNT-EYE-SDK#14]
0104 50 fps 500 Hz
0103 25 fps 500 Hz => special build

which one is better for slam?

**Comment by yangruixuan** [comment]
Try this one 0103 25 fps 500 Hz

**Comment by yangruixuan** [comment]
Or use the latest version

**Comment by ghost** [comment]
OK, I will try 0103 25 fps 500 Hz.

I have calibrated this camera to get 0.2 reprojection error and run ORB-SLAM2 Stereo in 50FPS,
but compared to ZED 30FPS, I got quite a bad result....

**Comment by derekhe89** [comment]
sorry,  I do not know your specific problem ，but 50FPS is too high, you can reduce the FPS by using 0103 or the newest version 0105. 25FPS is  appropriate for  my computer which cpu is intel Corei7-4710M.
