### ISSUE TITLE
Load .dll failed under GPU mode

### ISSUE THREAD

**Issue by hujyyy** [slightech/MYNT-EYE-SDK#16]
Hello, I just met a problem when I tried to run the sample program camera.exe. The error info looks like :

Open Camera: MYNTEYE
Compute Mode: MODE_AUTO_DETECT
Detect CUDA support
Load mynteye_cudafeatures.dll
Load mynteye_cudafeatures.dll failed: C:\.......\mynteye-1.8-win-x64-opencv-3.4.0\bin\mynteye_cudafeatures.dll

I've checked the path, and there's nothing wrong with it. It seems that it can't load the DLL file correctly.  However, when I switched on the CPU mode:
`cam.SetMode(Mode::MODE_CPU);`,
everything work out nicely. Also, the same thing occurred when I ran other sample programs.

The environment of my PC is win10-x64, CUDA8.0, OpenCV3.4.0.

**Comment by hujyyy** [comment]
Also, I purchased the camera with IR on it. I wonder does it share the same SDK with the standard version one since I didn't figure out how set up the IR camera on it. 
Thank you!

**Comment by yangruixuan** [comment]
You need use CUDA 9.0. IR version use the same SDK. You need use the latest version and see the API doc.

**Comment by hujyyy** [comment]
Well , thanks a lot! 
Another question is do the SDKs only use the stereo approach to calculate the depthmap or it use other things like structural light. I've checked all the sample programs, it seems that none of them use the IR camera when calculating the depthmap...
And the release note says that it added IR,HDR control API in 1.8 version on linux but I did't find it in the API doc.

Sorry for so many questions..hope you can help. Thank you!
