### ISSUE TITLE
Cannot run on ubuntu 14.04

### ISSUE THREAD

**Issue by skylook** [slightech/MYNT-EYE-SDK#19]
When I test your sample of camera and camera2 on ubuntu 14.04, it dies in several seconds. I also tried ROS wrapper on indigo, it crashes.
What can I do to make it work? Thanks.

**Comment by yangruixuan** [comment]
MYNT EYE 1.x SDK is no longer supported. Please upgrade to 2.x SDK and firmware
MYNT EYE 2.x SDK https://github.com/slightech/MYNT-EYE-SDK-2
MYNT EYE 2.x Guide https://slightech.github.io/MYNT-EYE-SDK-2-Guide/
