### ISSUE TITLE
Sample doesn't work

### ISSUE THREAD

**Issue by jinchenglee** [slightech/MYNT-EYE-SDK#2]
![Uploading mynteye_experiment.png…]()

Ubuntu 16.04 LTS, gcc 4.9.3, 64bit machine, OpenCV3.2.0 + CUDA8.0 successfully built/installed. 

Running sample in mynteye-1.5-linux-x64-gcc4-opencv-3.2.0/samples/bin/camera* will show some wired image seems not synchroized well, as attached image shows.

**Comment by jinchenglee** [comment]
Sample screenshot is here: https://drive.google.com/file/d/0B9UOI61E-lzBY3NIMkh1ZG9zRWM/view?usp=sharing

**Comment by jinchenglee** [comment]
OK, found the reason. It was not connected to the USB3.0 port. When I connect it to usb3.0 port, all sample applications can work. 

But, the ./app/Preview still cannot detect the device, although it is connected to usb3.0 host (xhci):
$ lsusb -t
/:  Bus 04.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/4p, 5000M
    |__ Port 4: Dev 2, If 0, Class=Video, Driver=uvcvideo, 5000M
    |__ Port 4: Dev 2, If 1, Class=Video, Driver=uvcvideo, 5000M
...

**Comment by joinAero** [comment]
Run `<sdk>/tools/list_devices`, could you find the device?

**Comment by joinAero** [comment]
Ensure `sudo apt-get install libv4l-dev v4l-utils`, then run `v4l2-ctl --list-devices`. Could you see the device?

`<sdk>/apps/Previewer` depends on `v4l-utils` to list the device. Select `Device > Reload` to refresh the device list.

Besides, check the environment variables after installation:

```
$ echo $MYNTEYE_SDK_ROOT
<Should be the sdk path>
```

**Comment by jinchenglee** [comment]
Thanks, after doing all these, the Preview app works. But it doesn't install anything though. 

Anyways, I'll close this ticket. 

$ sudo apt-get install libv4l-dev v4l-utils
[sudo] password for xxx: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libv4l-dev is already the newest version (1.10.0-1).
v4l-utils is already the newest version (1.10.0-1).
0 upgraded, 0 newly installed, 0 to remove and 60 not upgraded.
$ v4l2-ctl --list-devices
MYNTEYE (usb-0000:00:14.0-4):
	/dev/video0

$ echo $MYNTEYE_SDK_ROOT 
/blahblah/mynteye-1.5-linux-x64-gcc4-opencv-3.2.0

**Comment by jinchenglee** [comment]
BTW, may I know what camera sensor does MYNT EYE uses? Any details on what level of synchronization error is I can trust between camera and IMU? Thanks.

**Comment by joinAero** [comment]
Camera sensor: MT9V024

**Comment by joinAero** [comment]
Camera sensor: MT9V024

Synchronization error between camera and IMU (latest firmware): <1ms

**Comment by jinchenglee** [comment]
Is it possible to make it work with usb 2.0 at a lower frame rate? Although usb 3.0 is becoming popular, a lot of existing boards only have usb 2.0, say Raspberry Pi 3. 

Running at a lower fps is definitely acceptable comparing to no support at all.

**Comment by joinAero** [comment]
It is not possible now. However, our embedded software engineers will research it and reply here when there is a result.
