### ISSUE TITLE
Update Failed - Device not detected

### ISSUE THREAD

**Issue by sneheshs** [slightech/MYNT-EYE-SDK#21]
While updating the camera firmware, the update process did not complete even after 30 mins. So we reset the application and unplugged the device. Looks like the camera might be bricked. Can you please advise how to fix/ flash the firmware?

**Comment by yangruixuan** [comment]
Please follow the instructions and make sure you have installed the drivers
https://slightech.github.io/MYNT-EYE-SDK/upgrade_firmware.html
