### ISSUE TITLE
problem with IMU timing and synchronization

### ISSUE THREAD

**Issue by dymczykm** [slightech/MYNT-EYE-SDK#22]
Hi,
we wanted to make the Mynt-eye sensor to work with our maplab (https://github.com/ethz-asl/maplab/) mapping framework after calibrating it with Kalibr (https://github.com/ethz-asl/kalibr). The calibration, however, failed and we decided to take a look at rosbags generated from the sensor.

From what we noticed, there must be an issue with synchronizing the cameras with the IMU. 
1) When looking at the bag with rqt_bag, you can see that some IMU measurements are simply missing.
![rqt_bag](https://user-images.githubusercontent.com/6044558/38874219-e3b51406-4257-11e8-9b25-1322fb4c735f.png)

2) Additionally, we have examined the bag with Kalibr kalibr_bagextractor and calculated the timestamp increments between consecutive IMU measurements. As you can see, most of the increments are at 2,000,000 ns (which is 2ms = 500Hz) and this is fine. It happens quite often, however, that we get ~45ms drops and missing data. This prevents us from calibrating the sensor and using it for precise visual-inertial odometry.
![imu_sample_increments](https://user-images.githubusercontent.com/6044558/38874248-f221d588-4257-11e8-802a-976b9ae26c01.png)

We would like to ask if you have observed similar issues and are you aware of them? Would it be possible to fix the synchronization issues we are experiencing?

**Comment by yangruixuan** [comment]
You can try this new beta version https://github.com/slightech/MYNT-EYE-SDK-2

**Comment by schneith** [comment]
Unfortunately, the update got stuck and left us with a bricked sensor. In our recovery attempts, we flashed an image provided by a Cypress whitepaper to verify the FX3 is not dead; which worked without problems. But the default Cypress bootloader on the ROM doesn't seem to work with your update tool and we wonder whether you are using your own bootloader to flash images. Could you help us to recover the device?

**Comment by yangruixuan** [comment]
Please follow the instruction https://slightech.github.io/MYNT-EYE-SDK/upgrade_firmware.html

**Comment by schneith** [comment]
Thanks for the help. Unfortunately, these instructions didn't work out. The update tool remains in the update stage and didn't finish over night (+-12hrs). After the update the device still appears with the FX3 bootloader USB id. Do you have any other tips for us?

**Comment by dymczykm** [comment]
@yangruixuan we still can't flash the device properly, could you offer us some help?

**Comment by yangruixuan** [comment]
Of course, what's the problem now?

**Comment by dymczykm** [comment]
@yangruixuan so basically we started flashing the sensor according to your instructions (we got the "please wait" message with the rotating symbol), but nothing happened after over 12hrs, which doesn't seem to be correct.

We did run this process on an native Windows PC.

**Comment by yangruixuan** [comment]
@dymczykm Please install the WestBridge_driver and try again. The flashing should end within one minute. You can interrupt if the process in no response.

**Comment by protobits** [comment]
I see the same issue and I have updated camera to latest firmware and have the latest SDK (2.x). Why is this happening?

**Comment by yangruixuan** [comment]
@v01d What is the situation?

**Comment by protobits** [comment]
Besides other minor issues, the main problem is that I get Imu readings with timestamps before the image that was already sent. I'm guessing that this is due to the fact that imu readings are sent in batches, as can be seen in the above rqt_bag image. In other words, most imu readings arrive a bit late.

**Comment by protobits** [comment]
@yangruixuan  to clarify, the issue i'm describing is not exactly the same as the original one in this issue (the dropping of messages). maybe I should open a separate issue regarding the ordering of IMU/camera messages?

**Comment by yangruixuan** [comment]
You can try the re-stamped function mentioned in  slightech/MYNT-EYE-S-SDK#25
https://github.com/ethz-asl/dataset_tools/blob/master/python/restamp_bag.py

**Comment by yangruixuan** [comment]
@v01d OK
