### ISSUE TITLE
Load libmynteye_cudafeatures.so failed

### ISSUE THREAD

**Issue by hgpvision** [slightech/MYNT-EYE-SDK#25]
Hi~, I built the samples successfully and the cmake results show that I found the suitable exact CUDA version 8.0. The cmake result are as follows:

`-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- Using flag -std=c++11.
-- SDK_DIR: /home/hgpvision/Softwares/mynteye
-- SDK_LIB_DIR: /home/hgpvision/Softwares/mynteye/lib
-- LIB_MYNTEYE_CORE: libmynteye_core.so
-- OpenCV_DIR: /usr/local/opencv3.4.0
-- OpenCV_DIR changed: /usr/local/opencv3.4.0/share/OpenCV
-- Found CUDA: /usr/local/cuda-8.0 (found suitable exact version "8.0") 
-- OpenCV_VERSION: 3.4.0
-- OpenCV_LIBS: opencv_calib3d;opencv_core;opencv_cudaarithm;opencv_cudabgsegm;opencv_cudacodec;opencv_cudafeatures2d;opencv_cudafilters;opencv_cudaimgproc;opencv_cudalegacy;opencv_cudaobjdetect;opencv_cudaoptflow;opencv_cudastereo;opencv_cudawarping;opencv_cudev;opencv_dnn;opencv_features2d;opencv_flann;opencv_highgui;opencv_imgcodecs;opencv_imgproc;opencv_ml;opencv_objdetect;opencv_photo;opencv_shape;opencv_stitching;opencv_superres;opencv_video;opencv_videoio;opencv_videostab;opencv_viz;opencv_aruco;opencv_bgsegm;opencv_bioinspired;opencv_ccalib;opencv_datasets;opencv_dpm;opencv_face;opencv_freetype;opencv_fuzzy;opencv_hdf;opencv_img_hash;opencv_line_descriptor;opencv_optflow;opencv_phase_unwrapping;opencv_plot;opencv_reg;opencv_rgbd;opencv_saliency;opencv_stereo;opencv_structured_light;opencv_surface_matching;opencv_text;opencv_tracking;opencv_xfeatures2d;opencv_ximgproc;opencv_xobjdetect;opencv_xphoto
-- Configuring done
`

But I got the error when I tried to run ./camera 0:
`
Open Camera: 0
Compute Mode: MODE_AUTO_DETECT
Detect CUDA support
Load libmynteye_cudafeatures.so
Load libmynteye_cudafeatures.so failed: /home/hgpvision/Softwares/mynteye/lib/libmynteye_cudafeatures.so
Segmentation fault (core dumped)
'

I have no idea about this error. So what is wrong with it? 

Thanks and Best Regards,
hgpvision

**Comment by robotac** [comment]
I have the same question.My environment is TX2 cuda-9.0 openCV-3.1.1

**Comment by yangruixuan** [comment]
Normally, it's because the CUDA version not supported.

**Comment by yangruixuan** [comment]
Please try to upgrade to 2.x SDK and firmware
MYNT EYE 2.x SDK https://github.com/slightech/MYNT-EYE-SDK-2
MYNT EYE 2.x Guide https://slightech.github.io/MYNT-EYE-SDK-2-Guide/
