### ISSUE TITLE
Where can we purchase it?

### ISSUE THREAD

**Issue by rising-turtle** [slightech/MYNT-EYE-SDK#26]
Hi, is there any place that put this camera-imu suite on sale?  Or can anyone tells me how to get it? 
Thanks in advance.

**Comment by yangruixuan** [comment]
Worldwide: https://mynteyeai.com/products/mynt-eye-stereo-camera
China: https://xiaomishuma.tmall.com

**Comment by rising-turtle** [comment]
Thanks
