### ISSUE TITLE
Copyright issue

### ISSUE THREAD

**Issue by edwin323** [slightech/MYNT-EYE-SDK#27]
![zed-sdk-copy](https://user-images.githubusercontent.com/36691858/40187885-f132ca8e-59f8-11e8-9360-63d7201ef651.jpg)

**Comment by stevemartinov** [comment]
@gabriel-zed You can go and fuck yourself. Even if they copied your code their product is much better and at much lower price. So piss off as you guys are restricting the development of computer vision by tagging your camera at 500 quid.
