### ISSUE TITLE
Calibration data not being saved in SN*.conf

### ISSUE THREAD

**Issue by fiorano10** [slightech/MYNT-EYE-SDK#28]
I'm running Ubuntu 16.04. After I run the calibration script, it says the calibration has been saved in extrinsics.yml instead of SN*.conf.

**Comment by yangruixuan** [comment]
MYNT EYE 1.x SDK is no longer supported. Please upgrade to 2.x SDK and firmware
MYNT EYE 2.x SDK https://github.com/slightech/MYNT-EYE-SDK-2
MYNT EYE 2.x Guide https://slightech.github.io/MYNT-EYE-SDK-2-Guide/
