### ISSUE TITLE
ROS problem

### ISSUE THREAD

**Issue by dvalenciar** [slightech/MYNT-EYE-SDK#29]
Hello.
I already installed the MYNT EYE SDK  and everything looks good , also the SDK examples works without problem, but when I try to use it with  ROS i got the  next error:

[mynteye/mynteye_wrapper_node-2] process has died [pid 2494, exit code -11, cmd /home/joule1604/MYNT-EYE-SDK-2/wrappers/ros/devel/lib/mynt_eye_ros_wrapper/mynteye_wrapper_node __name:=mynteye_wrapper_node __log:=/home/joule1604/.ros/log/8525e74a-93e6-11e8-b451-a0c5892451a3/mynteye-mynteye_wrapper_node-2.log].

log file: /home/joule1604/.ros/log/8525e74a-93e6-11e8-b451-a0c5892451a3/mynteye-mynteye_wrapper_node-2*.log

The ROS  installation package   had finished without problems, I got that error with:
roslaunch mynt_eye_ros_wrapper mynteye.launch

Any idea why ?

thank you

**Comment by AWilson10** [comment]
Having exactly the same problem..  can you anyone shed any light?

**Comment by davidvar** [comment]
-----Original Message-----
