### ISSUE TITLE
Can't run the mynteye "./Previewer", the error message is :"Load libmynteye_cudafeatures.so failed: /home/turtle/mynteye-1.5-linux-x64-gcc5-opencv-3.2.0/lib/libmynteye_cudafeatures.so "

### ISSUE THREAD

**Issue by linhuixiao** [slightech/MYNT-EYE-SDK#3]
###################
My environment is Ubuntu 16.04 LTS, 64 bit, gcc 5.4.0, OpenCV 3.2.0, CUDA 9.0 version. the mynteye sdk I used is mynteye-1.5-linux-x64-gcc5-opencv-3.2.0.tar.gz

I installed according to the official documentation:  https://slightech.github.io/MYNT-EYE-SDK/getting_started_linux.html

###################
BUT! 

But when I runing the mynteye by using different methods, it was all failed, and the error message are the same:

root@turtle:~/mynteye-1.5-linux-x64-gcc5-opencv-3.2.0/apps# ./Previewer
("/home/turtle/mynteye-1.5-linux-x64-gcc5-opencv-3.2.0/apps/3rdparty", "/home/turtle/mynteye-1.5-linux-x64-gcc5-opencv-3.2.0/apps")
CaptureThread
Compute Mode: MODE_AUTO_DETECT
Detect CUDA support
Load libmynteye_cudafeatures.so
Load libmynteye_cudafeatures.so failed: /home/turtle/mynteye-1.5-linux-x64-gcc5-opencv-3.2.0/lib/libmynteye_cudafeatures.so
段错误 (核心已转储)

##################
I was try to reinstall the mynteye-1.5-linux-x64-gcc5-opencv-3.2.0.tar.gz , mynteye-1.4-linux-x64-gcc5-opencv-3.2.0.tar.gz , it shows the same error message.

I tried to start the desktop MYNTEYE icon, it also failed. 

the following shows:

root@turtle:~/mynteye-1.5-linux-x64-gcc5-opencv-3.2.0/samples/bin# ./camera
Open Camera: 0
Compute Mode: MODE_AUTO_DETECT
Detect CUDA support
Load libmynteye_cudafeatures.so
Load libmynteye_cudafeatures.so failed: /home/turtle/mynteye-1.5-linux-x64-gcc5-opencv-3.2.0/lib/libmynteye_cudafeatures.so
段错误 (核心已转储)
root@turtle:~/mynteye-1.5-linux-x64-gcc5-opencv-3.2.0/samples/bin# ./camera2
Open Camera: 0
Compute Mode: MODE_AUTO_DETECT
Detect CUDA support
Load libmynteye_cudafeatures.so
Load libmynteye_cudafeatures.so failed: /home/turtle/mynteye-1.5-linux-x64-gcc5-opencv-3.2.0/lib/libmynteye_cudafeatures.so
段错误 (核心已转储)

###############
it need pay special attention is: 

the opencv successfully passed the sample test:
$cd opencv/samples
$cmake
$make
$cd cpp/
$./cpp-example-example

the CUDA also successfully passed the sample test:
$cd /usr/local/cuda-9.0/samples/bin/x86_64/linux/release
$./deviceQuery

##############
That is my problem, If the MYNT eye can't run, My reasherch work will be unable to continue. It's very urgent for me, hope some good ones can help me to solve it, THANK YOU! !

**Comment by joinAero** [comment]
CUDA 9.0 is not available now.The SDK which built with CUDA 8 is not compatible with CUDA 9

**Comment by joinAero** [comment]
CUDA 9.0 is not available now.

The SDK 1.5 which built with CUDA 8 is not compatible with CUDA 9. You could learn more [here](https://slightech.github.io/MYNT-EYE-SDK/appendix_build_platforms.html).

Solution 1, uncomment `cam.SetMode(Mode::MODE_CPU)` in `<sdk>/samples/src/camera2.cc`, which enable CPU instead of CUDA:

    Camera cam;
    //cam.SetMode(Mode::MODE_CPU);
    cam.Open(init_params);

Solution 2, install CUDA 8.

Solution 3, wait several days, we will distribute SDK 1.6 which built with latest CUDA version  in this week.

**Comment by joinAero** [comment]
SDK v1.6 is released.
