### ISSUE TITLE
My MYNT-EYE upgrade firmware Incorrect operation and  make error, confirm "Device" is selected as "N/A".

### ISSUE THREAD

**Issue by linhuixiao** [slightech/MYNT-EYE-SDK#4]
I'm sorry,  I use the MYNT-EYE  release 1.6 today, It reminded me that I need to upgrade the firmware.
I followed the tutorial https://slightech.github.io/MYNT-EYE-SDK/upgrade_firmware.html , and click  .exe  to download the camera tool. 
#############
BUT!! 
On the upgrade window, confirm "Device" is selected as "MYNTEYE".  It's OK, 
But after I click "Update" on right side, and I select the C:\Program Files (x86)\Slightech\CyBootProgrammer.img, and to upgrade.

I'm sorry I didn't realize the "mynteye_*.img" file need to download in another github load.  It was not all my fault, the tutorial didn't say yet.

###########
Now, I realized I was wrong, I chose to upgrade again , However, On the upgrade window, confirm "Device" is selected as "N/A".

What should I do? Is there any detail solution ? 

It's very urgent for me, hope some good ones can help me, THANK YOU! !

**Comment by linhuincu** [comment]
I let the mynteye connect the Ubuntu 16.04 MYNT EYE, it 's shows MYNTEYE not found. I am so sorry that wanna to cry.. what should I do.   My e-mail is linhui.xiao@foxmail.com .  THANK YOU !!!

**Comment by linhuixiao** [comment]
OK, I have solved this problem according to the tutorial document below. THANK YOU!
