### ISSUE TITLE
The mynt eye can not run in ubuntu already! CUDA Error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by linhuixiao** [slightech/MYNT-EYE-SDK#5]
##################
My environment is Ubuntu 16.04 LTS, 64 bit, gcc 5.4.0, OpenCV 3.2.0, CUDA 9.0 version. the mynteye sdk I used is mynteye-1.6-linux-x64-gcc5-opencv-3.2.0.tar.gz , and the mynteye firmware is mynteye_0104_1711031837.img

##################
the following is the error message:

##########
root@turtle:/opt/mynteye-1.6-linux-x64-gcc5-opencv-3.2.0# ./apps/Previewer
("/opt/mynteye-1.6-linux-x64-gcc5-opencv-3.2.0/apps/3rdparty", "/opt/mynteye-1.6-linux-x64-gcc5-opencv-3.2.0/apps")
CaptureThread
Compute Mode: MODE_AUTO_DETECT
Detect CUDA support
Load libmynteye_cudafeatures.so
Load libmynteye_cudafeatures.so done
Saved the camera's infomation to a temporary file:
  /opt/mynteye-1.6-linux-x64-gcc5-opencv-3.2.0/settings/mynteye.info.temp
Open Camera ..
Saved the camera's infomation to a temporary file:
  /opt/mynteye-1.6-linux-x64-gcc5-opencv-3.2.0/settings/mynteye.info.temp
V4L2_CID_GAIN: min=0, max=48, default=24
V4L2_CID_BRIGHTNESS: min=0, max=240, default=120
V4L2_CID_CONTRAST: min=0, max=254, default=127
V4L2_CID_EXPOSURE_AUTO: min=0, max=1, default=0
V4L2_CID_EXTENSION is supported
CUDA Error: no kernel image is available for execution on the device
QObject::~QObject: Timers cannot be stopped from another thread
段错误 (核心已转储)

##########
root@turtle:/opt/mynteye-1.6-linux-x64-gcc5-opencv-3.2.0# ./samples/bin/camera2
Open Camera: 0
Compute Mode: MODE_AUTO_DETECT
Detect CUDA support
Load libmynteye_cudafeatures.so
Load libmynteye_cudafeatures.so done
Saved the camera's infomation to a temporary file:
  /opt/mynteye-1.6-linux-x64-gcc5-opencv-3.2.0/settings/mynteye.info.temp
V4L2_CID_GAIN: min=32, max=48, default=32
V4L2_CID_BRIGHTNESS: min=-10, max=10, default=0
V4L2_CID_CONTRAST: min=0, max=20, default=10
V4L2_CID_EXPOSURE_AUTO: min=-5, max=5, default=0
V4L2_CID_EXTENSION is supported
Press ESC/Q on Windows to terminate
init done
CUDA Error: no kernel image is available for execution on the device
QMutex: destroying locked mutex
QObject::~QObject: Timers cannot be stopped from another thread
段错误 (核心已转储)

############
where is wrong? thank you!

**Comment by linhuixiao** [comment]
I run the MYNT EYE app and chose the CPU mode it can run normally, but my computer has GPU nvidia GTX 635.

**Comment by joinAero** [comment]
On [CUDA GPUs](https://developer.nvidia.com/cuda-gpus) page, I didn't find what's the compute capability of GTX 635.

Please run `deviceQuery` in CUDA samples, and let us know your GPU's compute capability.

This error information is [here](http://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html), search `cudaErrorNoKernelImageForDevice`:

> This indicates that there is no kernel image available that is suitable for the device. This can occur when a user specifies code generation options for a particular CUDA source file that do not include the corresponding device configuration.

Our CUDA nvcc flags are:

> -std=c++11;-use_fast_math;-gencode;arch=compute_30,code=sm_30;-gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-D_FORCE_INLINES

Maybe we don't include the gencode of your GPU now.
