### ISSUE TITLE
HDR (high dynamic range) raw image

### ISSUE THREAD

**Issue by jinchenglee** [slightech/MYNT-EYE-SDK#9]
MT9V024 is a HDR sensor, what mode is set when output is received from host PC side? In  MT9V024 datasheet, 10bit/12-bit companding is involved in certain mode. How is HDR -> SDR convertion is done before sending output image data over USB?

Is there a way to grab raw sensor data for dynamic range processing on host PC if no HDR processing is involved in SDK?

**Comment by jinchenglee** [comment]
[http://www.onsemi.com/pub/Collateral/MT9V024-D.PDF](http://www.onsemi.com/pub/Collateral/MT9V024-D.PDF), MT9V024 datasheet.

**Comment by joinAero** [comment]
There are exactly two modes: 10bit mode, 12bit-to-10bit mode.

By default, 10bit mode is set. And the mode can not be changed now, until next realeased firmware (provides a control api to set it).

Whatever the mode is, the output image data format is same.

But in 12bit-to-10bit mode, the sensor is more sensitive to the light. You should reduce the desired brightness through the control api.

**Comment by jinchenglee** [comment]
Even for the 10-bit mode, users don't get a whole 10-bit, right? I guess it is only 8-bit, so the SDK does a  convenient cut-last-two-LSB bits?

This is not cool for dark/night scenes.

**Comment by joinAero** [comment]
SDK 1.8 added HDR control api, you could change the mode.
